<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Forgot Password</name>
   <tag></tag>
   <elementGuidId>11293841-8d94-4041-9ef0-f3f30f28e472</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='forgotPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#forgotPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7a9c19f9-d00a-42d7-ac3c-c505a69dc60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>forgotPassword</value>
      <webElementGuid>8ba86c65-77bf-4ea2-a340-e71fd51ea9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cgappstest.onmicrosoft.com/B2C_1A_signup_signin/api/CombinedSigninAndSignup/forgotPassword?csrf_token=WDZlUDVIODcxRCtra1dwUHB4RjN3akxnVmJFNy8xdjRQSmdWcXlGajBKaHY3eEFIL1Y5VzBZb0NZRVNyS1Z3UHpUbTZOTnJBUDRoY2RuMkhvSVJ4NXc9PTsyMDI1LTAxLTMxVDE3OjA3OjEzLjc3ODIyMDZaO09WeXQ4b3lpeGl4dEZvVjc4YUkxRkE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjoyfQ==&amp;tx=StateProperties=eyJUSUQiOiIwMGE1MzI2ZC02NzRkLTQwNDMtODg3ZS02YjE2NTUzMjAxNzUifQ&amp;p=B2C_1A_signup_signin</value>
      <webElementGuid>bae31e82-a6cd-43f5-a1d8-2ee8d4908d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot your password?</value>
      <webElementGuid>df9eab95-5b41-4358-a0cd-686c4a809647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgotPassword&quot;)</value>
      <webElementGuid>321325c9-d29a-428b-9815-855c93af2393</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='forgotPassword']</value>
      <webElementGuid>65a57516-8b43-4a3b-8605-c755c5fc2004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='localAccountForm']/div[3]/div[2]/div/a</value>
      <webElementGuid>b2df436c-53fc-4d29-8b10-d16d51ae728b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot your password?')]</value>
      <webElementGuid>7be814e6-4209-4fbd-89f2-26995e3b0005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::a[1]</value>
      <webElementGuid>f0df3f0f-c89e-4cb4-83e2-87cfa8d1a886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in name'])[1]/following::a[1]</value>
      <webElementGuid>661ac0d4-b927-4a20-b2ed-bd5e7fbb39f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::a[1]</value>
      <webElementGuid>d34f5d38-1642-4102-9f3b-008a22599e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[2]/preceding::a[1]</value>
      <webElementGuid>816911f9-6b83-4421-a0cd-17776aa039db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot your password?']/parent::*</value>
      <webElementGuid>bfd35505-aab5-4e1f-b142-dbdcb57d1d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cgappstest.onmicrosoft.com/B2C_1A_signup_signin/api/CombinedSigninAndSignup/forgotPassword?csrf_token=WDZlUDVIODcxRCtra1dwUHB4RjN3akxnVmJFNy8xdjRQSmdWcXlGajBKaHY3eEFIL1Y5VzBZb0NZRVNyS1Z3UHpUbTZOTnJBUDRoY2RuMkhvSVJ4NXc9PTsyMDI1LTAxLTMxVDE3OjA3OjEzLjc3ODIyMDZaO09WeXQ4b3lpeGl4dEZvVjc4YUkxRkE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjoyfQ==&amp;tx=StateProperties=eyJUSUQiOiIwMGE1MzI2ZC02NzRkLTQwNDMtODg3ZS02YjE2NTUzMjAxNzUifQ&amp;p=B2C_1A_signup_signin')]</value>
      <webElementGuid>f9e005f2-9706-4805-8c68-2d71baebd5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>63fcb255-11e9-4c44-a8a5-cc28641d7db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'forgotPassword' and @href = '/cgappstest.onmicrosoft.com/B2C_1A_signup_signin/api/CombinedSigninAndSignup/forgotPassword?csrf_token=WDZlUDVIODcxRCtra1dwUHB4RjN3akxnVmJFNy8xdjRQSmdWcXlGajBKaHY3eEFIL1Y5VzBZb0NZRVNyS1Z3UHpUbTZOTnJBUDRoY2RuMkhvSVJ4NXc9PTsyMDI1LTAxLTMxVDE3OjA3OjEzLjc3ODIyMDZaO09WeXQ4b3lpeGl4dEZvVjc4YUkxRkE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjoyfQ==&amp;tx=StateProperties=eyJUSUQiOiIwMGE1MzI2ZC02NzRkLTQwNDMtODg3ZS02YjE2NTUzMjAxNzUifQ&amp;p=B2C_1A_signup_signin' and (text() = 'Forgot your password?' or . = 'Forgot your password?')]</value>
      <webElementGuid>14d37c65-1aef-4287-9f49-91c733aaaaa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
