<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Google Login</name>
   <tag></tag>
   <elementGuidId>d3d00158-8783-458c-ae6e-7f737f46e69b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='GoogleExchange']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GoogleExchange</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f672b3f0-3f9e-4199-b08c-a86624f8bcf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accountButton claims-provider-selection</value>
      <webElementGuid>7f739dfb-6466-4dc7-8d8b-969664b627c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GoogleExchange</value>
      <webElementGuid>47b61bc5-0e73-4803-b79f-4b374996aa89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>492f8e43-f60e-4367-aec5-14bd03d0e8f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Google</value>
      <webElementGuid>c7b230a5-f38c-493d-914e-e1a7f4faf970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GoogleExchange&quot;)</value>
      <webElementGuid>d9e6c2bf-8f70-4149-9e9e-108a759b2aca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='GoogleExchange']</value>
      <webElementGuid>719d8f1e-911a-4e13-886c-be813161db3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='api']/div/div[2]/div[2]/button</value>
      <webElementGuid>cf33691c-e5d1-44be-8ed4-1b440831ec2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/following::button[1]</value>
      <webElementGuid>fb39bfcf-5ebf-4e99-87a5-dbaf672da52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in with your social account'])[1]/following::button[2]</value>
      <webElementGuid>8ad0c8d1-dd12-40d5-9d6c-570d80188656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Microsoft Account'])[1]/preceding::button[1]</value>
      <webElementGuid>bf721498-e448-4bbd-a30a-aff4c7e1371d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/preceding::button[2]</value>
      <webElementGuid>0f27ccdc-4adf-4236-a39a-8d8286bbefb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Google']/parent::*</value>
      <webElementGuid>5c97ac84-afac-4932-974d-ec23175ad1a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>298422f0-4c5c-49ab-bd21-9f4677a712fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'GoogleExchange' and (text() = 'Google' or . = 'Google')]</value>
      <webElementGuid>cd9be6ec-93a3-4fe7-9ee2-6fa21c7af18a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
