<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sign up</name>
   <tag></tag>
   <elementGuidId>97fa5bae-20cd-43c7-bc2b-b1d339618357</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='createAccount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#createAccount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>002a471c-d479-4a29-bb25-532a1c2687f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>createAccount</value>
      <webElementGuid>df4d092d-bfab-4269-850b-3723e50bd4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cgappstest.onmicrosoft.com/B2C_1A_signup_signin/api/CombinedSigninAndSignup/unified?local=signup&amp;csrf_token=WDZlUDVIODcxRCtra1dwUHB4RjN3akxnVmJFNy8xdjRQSmdWcXlGajBKaHY3eEFIL1Y5VzBZb0NZRVNyS1Z3UHpUbTZOTnJBUDRoY2RuMkhvSVJ4NXc9PTsyMDI1LTAxLTMxVDE3OjA3OjEzLjc3ODIyMDZaO09WeXQ4b3lpeGl4dEZvVjc4YUkxRkE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjoyfQ==&amp;tx=StateProperties=eyJUSUQiOiIwMGE1MzI2ZC02NzRkLTQwNDMtODg3ZS02YjE2NTUzMjAxNzUifQ&amp;p=B2C_1A_signup_signin</value>
      <webElementGuid>9962f832-7403-46c7-a00a-ed497f655c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign up now</value>
      <webElementGuid>16980822-4d02-461b-a342-a7ce7952c353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createAccount&quot;)</value>
      <webElementGuid>de38d831-a5ee-4da1-99c7-39bd4af69e41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='createAccount']</value>
      <webElementGuid>c967d6ad-368c-4d59-92cd-f416c6ed6af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='localAccountForm']/div[5]/p/a</value>
      <webElementGuid>829eaf99-9028-49f1-a35e-8f1fc8a3ff81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign up now')]</value>
      <webElementGuid>1dd03358-082b-42ab-a52d-6f7e7cbf6c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[2]/following::a[1]</value>
      <webElementGuid>7d3f08cc-397b-42d1-afe1-5dc5b5868964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::a[1]</value>
      <webElementGuid>4de7728b-cbf5-4483-82a0-bb544e877866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign up now']/parent::*</value>
      <webElementGuid>29b36ab4-fc3e-4dd3-8abe-5d4a82d8d0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cgappstest.onmicrosoft.com/B2C_1A_signup_signin/api/CombinedSigninAndSignup/unified?local=signup&amp;csrf_token=WDZlUDVIODcxRCtra1dwUHB4RjN3akxnVmJFNy8xdjRQSmdWcXlGajBKaHY3eEFIL1Y5VzBZb0NZRVNyS1Z3UHpUbTZOTnJBUDRoY2RuMkhvSVJ4NXc9PTsyMDI1LTAxLTMxVDE3OjA3OjEzLjc3ODIyMDZaO09WeXQ4b3lpeGl4dEZvVjc4YUkxRkE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjoyfQ==&amp;tx=StateProperties=eyJUSUQiOiIwMGE1MzI2ZC02NzRkLTQwNDMtODg3ZS02YjE2NTUzMjAxNzUifQ&amp;p=B2C_1A_signup_signin')]</value>
      <webElementGuid>1ed82848-b698-419c-88a0-0184e75d0be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>639d6570-9580-4a5f-8079-f23a128e7e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'createAccount' and @href = '/cgappstest.onmicrosoft.com/B2C_1A_signup_signin/api/CombinedSigninAndSignup/unified?local=signup&amp;csrf_token=WDZlUDVIODcxRCtra1dwUHB4RjN3akxnVmJFNy8xdjRQSmdWcXlGajBKaHY3eEFIL1Y5VzBZb0NZRVNyS1Z3UHpUbTZOTnJBUDRoY2RuMkhvSVJ4NXc9PTsyMDI1LTAxLTMxVDE3OjA3OjEzLjc3ODIyMDZaO09WeXQ4b3lpeGl4dEZvVjc4YUkxRkE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjoyfQ==&amp;tx=StateProperties=eyJUSUQiOiIwMGE1MzI2ZC02NzRkLTQwNDMtODg3ZS02YjE2NTUzMjAxNzUifQ&amp;p=B2C_1A_signup_signin' and (text() = 'Sign up now' or . = 'Sign up now')]</value>
      <webElementGuid>b1ace294-da94-4ba1-960d-dc2db549a1c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
