<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Country</name>
   <tag></tag>
   <elementGuidId>fec54989-494b-475c-8ac7-ed80c028eab3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCountry']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtCountry</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71f91647-f6fe-4812-ba31-855a867661f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4ac3d365-8c83-4e58-bd8c-a00dc1a245d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control validate</value>
      <webElementGuid>7590cabb-ae22-426e-85e3-1a87931479dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCountry</value>
      <webElementGuid>1f9a0602-2d13-40f4-a233-1bd6f059e91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>txtCountry</value>
      <webElementGuid>8701f5fc-449f-4d47-a01b-b5d6459bdfbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Country</value>
      <webElementGuid>5fb7528a-f3b9-44a4-9d4f-a089234401f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cgs-require</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>688cee58-b9dd-4df8-ad6d-8a3537e70d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cgs-error</name>
      <type>Main</type>
      <value>Please enter country</value>
      <webElementGuid>9bd0455e-800c-459e-b33a-151cad1964a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cgs-display</name>
      <type>Main</type>
      <value>fcountry_error</value>
      <webElementGuid>c5fe9b53-7859-4f3f-9d02-bb44cfe0a2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCountry&quot;)</value>
      <webElementGuid>faa74925-fa7a-4e0b-8a4b-096791553e72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCountry']</value>
      <webElementGuid>e2d8acb7-01c3-4023-a29c-dff576c08607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-details']/div/div[5]/div/input</value>
      <webElementGuid>a5f48f92-e892-4474-9327-4c1689a36657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div[5]/div/input</value>
      <webElementGuid>f271f966-4432-4019-865b-f096db2d3d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtCountry' and @placeholder = 'Country']</value>
      <webElementGuid>7e972ae8-e32f-4d29-a397-6e56dd69589b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
