<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email ID</name>
   <tag></tag>
   <elementGuidId>3d765510-acfe-4014-9fc4-6c677ff9da81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18d2991b-b65f-45b0-a9a1-876db4052265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>29bd2178-be73-4f2b-b6db-3b24df43f83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control validate</value>
      <webElementGuid>2d3f9a96-b059-431a-a039-072291db3bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtEmail</value>
      <webElementGuid>1f8eb2f4-7263-491d-887f-73ff93dbfcae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>txtEmail</value>
      <webElementGuid>c22e8b0a-1c4f-4d80-a164-b7f431db80ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email ID</value>
      <webElementGuid>fbbbb130-253e-474d-867d-c7af71c22c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cgs-require</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bdaf6f81-40ec-48a2-ad8c-d1a71c62270f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cgs-error</name>
      <type>Main</type>
      <value>Please enter email id</value>
      <webElementGuid>5951cbea-3866-48f8-8ab4-36b8612735c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cgs-email</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1e3fc860-3d19-485e-bd6c-27c4ff258492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cgs-email-error</name>
      <type>Main</type>
      <value>Please enter valid email</value>
      <webElementGuid>98e5eed6-80e8-4416-b209-4e8ea54e4e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cgs-display</name>
      <type>Main</type>
      <value>femail_error</value>
      <webElementGuid>0e35b176-0d07-4e55-8a0e-5bfffbbcd91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtEmail&quot;)</value>
      <webElementGuid>bcbe06ad-4732-438e-afd2-12cf707cbc29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtEmail']</value>
      <webElementGuid>c15a34f3-af2d-41f4-a84e-af3d6b2d1282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-details']/div/div[6]/div/input</value>
      <webElementGuid>87491b4c-eacc-4114-9811-0defed29b5fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>27ca353d-0fd2-4835-b435-4eaefc75f400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'txtEmail' and @placeholder = 'Email ID']</value>
      <webElementGuid>e3cfc669-28b1-4524-a754-3667daaa7def</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
