<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Enter Delete Code</name>
   <tag></tag>
   <elementGuidId>237f8072-d6c0-4d50-babe-7d98570990ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDeleteCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtDeleteCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75c4b017-c89b-4af1-a730-460930576768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDeleteCode</value>
      <webElementGuid>b4ff7474-be44-403e-b2ea-8c21cf530c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-lg text-center</value>
      <webElementGuid>209bf381-171e-4a6b-8b7e-60323f86f659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41cc62f3-6d7b-49b2-9616-7b6f6f1ce62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type code here</value>
      <webElementGuid>8443245c-efe3-4607-bbae-9960f05ddb89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDeleteCode&quot;)</value>
      <webElementGuid>7fab125d-d10f-4b18-b908-c2f6ff75ccb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDeleteCode']</value>
      <webElementGuid>5eada593-b112-44bd-8c91-12fb9273618d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupDeleteOrganization']/div/div/div[2]/div[2]/div[3]/input</value>
      <webElementGuid>09ceeba1-9fbd-4231-a2a2-c9d3e20bd628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>5a74d80e-ca86-42a0-9f94-2cf96f1ad0c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtDeleteCode' and @type = 'text' and @placeholder = 'Type code here']</value>
      <webElementGuid>1b4c02b7-5d95-4bcb-9b8f-cd1ae3e27a88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
