<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Mark_Kat_Org1</name>
   <tag></tag>
   <elementGuidId>12a01f69-0d14-47d3-999f-8179bcb07584</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Kat_Org1']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mark.animate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mark</value>
      <webElementGuid>753dd836-05f8-440a-90ba-b1839e1b405f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-markjs</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>09578814-7f02-4661-8d56-ae8bfbca7e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>animate</value>
      <webElementGuid>82d47df2-d0de-45cd-abf8-11854774e020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kat_Org1</value>
      <webElementGuid>72666053-6fbf-431f-bdca-34fc500a5a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;org_02C75B4A-8E29-4552-B290-9F73CC116846&quot;)/div[@class=&quot;card shadow-none bg-transparent&quot;]/a[@class=&quot;card-body&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;flex-grow-1 ms-3&quot;]/h4[@class=&quot;card-title text-truncate mb-1&quot;]/mark[@class=&quot;animate&quot;]</value>
      <webElementGuid>d230aed0-a72e-4312-9e2a-74033507c476</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kat_Org1']/parent::*</value>
      <webElementGuid>5f5ecfa6-0e31-4607-add2-7f375decbac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mark[(text() = 'Kat_Org1' or . = 'Kat_Org1')]</value>
      <webElementGuid>316a338f-748b-47ad-914e-51ea51b68e76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
