<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Modify</name>
   <tag></tag>
   <elementGuidId>44df9244-996e-4486-909d-76cc372ee294</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Modify']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-flat-primary.btn-edit-org.waves-effect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0d1727c4-2824-4568-b297-01453c86321f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fc3b6b0c-52d9-4c92-8e64-7d26e03a252d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-flat-primary btn-edit-org waves-effect</value>
      <webElementGuid>530608f7-62e9-4298-9802-4dee68819980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>02C75B4A-8E29-4552-B290-9F73CC116846</value>
      <webElementGuid>7c580b5a-9d18-4669-ae6b-b367b1b8dae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>btnModify</value>
      <webElementGuid>4f6a3f19-ca53-467e-b24c-96c8062c1955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Modify</value>
      <webElementGuid>e578339c-936f-4d61-88f7-f16dc7e72acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;org_02C75B4A-8E29-4552-B290-9F73CC116846&quot;)/div[@class=&quot;card shadow-none bg-transparent&quot;]/div[@class=&quot;card-footer text-muted p-3 pt-0 border-0&quot;]/div[@class=&quot;float-end&quot;]/button[@class=&quot;btn btn-flat-primary btn-edit-org waves-effect&quot;]</value>
      <webElementGuid>7ee3fe30-7e52-490c-b34e-ae109b789672</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='org_02C75B4A-8E29-4552-B290-9F73CC116846']/div/div/div/button[2]</value>
      <webElementGuid>2a982417-6dcc-4645-bce2-487bd8d14bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenants'])[1]/following::button[1]</value>
      <webElementGuid>b9fed018-5dcf-4e15-b974-18dc08353d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::button[1]</value>
      <webElementGuid>2579a256-952c-4200-b16f-69eca12e4fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Organization'])[1]/preceding::button[1]</value>
      <webElementGuid>d8776de3-bc26-4ea8-a015-288c0f3071df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::button[2]</value>
      <webElementGuid>62981ed6-6ef0-49cf-80d5-955fac80019f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Modify']/parent::*</value>
      <webElementGuid>7062d426-168e-44d8-b606-a509b06ec1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>54df60a6-c564-4ac1-8d2f-abec6c977432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Modify' or . = ' Modify')]</value>
      <webElementGuid>04976768-e0b8-49a0-848b-599bad3ad9a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
