<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>New Organization</name>
   <tag></tag>
   <elementGuidId>22d4fb06-65ef-41e3-8bed-50fc3fb839e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnNewOrg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnNewOrg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bb874794-0e12-401e-85f4-213776cf9e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn waves-effect waves-float ms-2 btn-success btn-sm</value>
      <webElementGuid>e3a86278-21b7-4406-9971-6acb5ddc0717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#orgOffcanvas</value>
      <webElementGuid>f4f80f66-9289-4561-b320-2a1f527e2a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>offcanvas</value>
      <webElementGuid>7d33736b-0c2f-4fe0-b4fa-d1f3424a7805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>btnNewOrg</value>
      <webElementGuid>2bcdaf16-ec0e-4e29-a466-d35b1c63a63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnNewOrg</value>
      <webElementGuid>8b0b2418-fa54-4c78-a19c-a48428aac9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> New Organization</value>
      <webElementGuid>87bd4dac-94f4-4f8e-9b72-2052bda1c64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnNewOrg&quot;)</value>
      <webElementGuid>31641f42-4dc8-4cda-9b67-7f033e60e33a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnNewOrg']</value>
      <webElementGuid>05bb1bc2-3e51-4f4a-a851-f29fd3abe2f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hdrSettings']/div/div/div[2]/div/button</value>
      <webElementGuid>e5b35aa1-640d-4946-a899-3b691244d8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organizations'])[3]/following::button[1]</value>
      <webElementGuid>f17c007b-51b3-4425-987a-10e5cadbc847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/following::button[1]</value>
      <webElementGuid>812916f3-50b6-45a7-94da-e4028614470c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show'])[1]/preceding::button[1]</value>
      <webElementGuid>c2a31a5b-ca89-4007-89d6-0cf70d9bdec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='entries'])[1]/preceding::button[1]</value>
      <webElementGuid>dd311357-4c78-47fc-a9f1-23d416b64fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New Organization']/parent::*</value>
      <webElementGuid>02d179e0-6583-4e7e-b0ce-9605571ca89d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>c085f4c5-61c3-4a8e-8bbe-c3fd7e7ffb2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnNewOrg' and (text() = ' New Organization' or . = ' New Organization')]</value>
      <webElementGuid>667e882b-c86b-420f-a8f2-f0cc67e526a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
