<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Phone Number</name>
   <tag></tag>
   <elementGuidId>b1a8f5f0-7431-4df8-b72f-9a97b50bf550</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPhone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtPhone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e69107d-f451-41da-8395-2a07c9867817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>86d33b6c-1ac0-4224-9dc7-4823163dc83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control validate</value>
      <webElementGuid>95f6ece7-1749-4895-add2-a52663095138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPhone</value>
      <webElementGuid>ae076b49-635b-4f1e-b42c-2bd5479a260d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>txtPhone</value>
      <webElementGuid>ac574ad1-3b3e-4497-9279-ed258ed2aeb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone Number</value>
      <webElementGuid>e5518422-572d-49b6-8eab-4e00c23336b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cgs-require</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8c42410a-0d0c-442c-a420-7e1c3973eb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cgs-error</name>
      <type>Main</type>
      <value>Please enter phone number</value>
      <webElementGuid>637cfdb9-87f9-427c-b575-1c567570f532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cgs-phone</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>01d45e85-b43b-498b-a435-8cac5fc727bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cgs-phone-error</name>
      <type>Main</type>
      <value>Please enter valid phone number</value>
      <webElementGuid>62850ea3-8b2f-4e58-bfeb-7fdda594c314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cgs-display</name>
      <type>Main</type>
      <value>fphone_error</value>
      <webElementGuid>b97bf86c-7347-4a46-a7ba-7e21e4d4d430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPhone&quot;)</value>
      <webElementGuid>70c2e61f-5da6-497e-9a33-50ecbfc0c7de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPhone']</value>
      <webElementGuid>411a6b9f-b9c9-4faa-b1ba-d3a6412b8224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-details']/div/div[7]/div/input</value>
      <webElementGuid>8c96d64e-5019-48aa-8918-cbbf5cf65e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>7514334a-69ca-42d4-a90b-2d3cd2c4d08b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtPhone' and @placeholder = 'Phone Number']</value>
      <webElementGuid>2a423459-5f88-4daf-9dcf-abe79996f1f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
