<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Save Organization</name>
   <tag></tag>
   <elementGuidId>519b19b9-4ef6-4871-9097-4e73a4a262a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnSaveOrg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnSaveOrg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>048fb4d4-0295-492d-b53b-f7d61755f5e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn w-sm waves-effect waves-float btn-primary btn-sm</value>
      <webElementGuid>c29d8d2e-a87e-488e-ab8c-ed4967cf9523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>btnCreateOrganization</value>
      <webElementGuid>c09c8a29-b428-4a9b-9ece-a74687532617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSaveOrg</value>
      <webElementGuid>6efd021b-aac2-41ec-bb9a-001a85638618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2f16f48e-719c-4a37-ba72-63917cb05668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Organization</value>
      <webElementGuid>d8041c53-51a7-405a-8ce0-8a305b2a0810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSaveOrg&quot;)</value>
      <webElementGuid>57cfd80c-3a02-48f4-a2b0-475652f8cf22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnSaveOrg']</value>
      <webElementGuid>62d07f61-1cc6-4fba-a4dd-d6ea7417a4ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orgOffcanvas']/div[3]/button[4]</value>
      <webElementGuid>756b30e2-e7d3-4a57-86c6-d09c098a1d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/following::button[1]</value>
      <webElementGuid>a06b0c7a-6229-4c72-8e2c-23cf3a1972f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::button[2]</value>
      <webElementGuid>c9f45d4f-b4dd-46bc-84aa-28e07bbdde9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Website powered by'])[1]/preceding::button[1]</value>
      <webElementGuid>f024fb33-b960-46af-a6b6-0212a93c0500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CommonGoals Software'])[1]/preceding::button[1]</value>
      <webElementGuid>b9ec6438-1dd4-4e9b-b2b2-fc732a82829f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Organization']/parent::*</value>
      <webElementGuid>20004027-6c87-40bb-a355-8bf8bc4259f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>1a0a6518-4613-4a96-8dfb-74d861f25eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnSaveOrg' and @type = 'button' and (text() = 'Create Organization' or . = 'Create Organization')]</value>
      <webElementGuid>265de698-8647-4bc1-b10f-baecd2754eba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
