<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search Organization</name>
   <tag></tag>
   <elementGuidId>caa21257-dee6-4b00-afdc-a346b4a221ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtSearchOrganization']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtSearchOrganization</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd24e3f5-9c96-41f7-87d3-c0ef0b80d392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtSearchOrganization</value>
      <webElementGuid>9cb65c8b-f320-46d6-b2c3-6583d7f1f459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtSearchOrganization-name-an</value>
      <webElementGuid>5da3d052-0237-4cfd-af95-f0460c3a757d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>38a3600c-9491-4cf5-bcea-386aa88e2de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-search</value>
      <webElementGuid>dfbc157d-7c48-4d2a-820a-6eb191163cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b63c85b-b7a0-41b8-80b0-863c0ab09a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>txtSearchOrganization</value>
      <webElementGuid>3f3c6322-542d-40b7-81bd-b78bdf564672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type to search organizations by name</value>
      <webElementGuid>d97550c5-e77e-47cd-b820-a6b3b1a7fb2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSearchOrganization&quot;)</value>
      <webElementGuid>56dd31e7-13fe-491f-ab64-fcb9dbb9fb71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtSearchOrganization']</value>
      <webElementGuid>fdeb1e58-7c84-4603-8cbb-8cfb480274cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filterContainer']/div/div/input</value>
      <webElementGuid>d9075bc4-56a4-4b77-aee0-062d639a97f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/div/div/input</value>
      <webElementGuid>961f0774-1825-4a18-821e-a12949b515d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtSearchOrganization' and @name = 'txtSearchOrganization-name-an' and @type = 'text' and @placeholder = 'Type to search organizations by name']</value>
      <webElementGuid>dde488e7-e1b2-42b3-94f8-8795dc61ef19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
