<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ZipPostal Code</name>
   <tag></tag>
   <elementGuidId>cfaf9942-8b5a-45d4-b0d2-f00c555b62af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtZip']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtZip</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b08915d2-92cf-406b-97ca-db3b0bad0274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>347b34ab-7b0f-4811-925b-54e17389540b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control validate</value>
      <webElementGuid>716a034a-6682-48b8-9375-dcc78985f415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtZip</value>
      <webElementGuid>6badca07-b923-42d3-a12a-c4b5740bf8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>txtZip</value>
      <webElementGuid>fdfba8ff-dc25-4c72-a25b-1f3258525bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Zip/Postal Code</value>
      <webElementGuid>11f07813-ca95-4036-85b7-becbacc5c371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cgs-require</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>72a0b5fc-1cf3-4bbd-8176-bd4142ab4745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cgs-error</name>
      <type>Main</type>
      <value>Please enter zip</value>
      <webElementGuid>18124de6-aff6-4880-9b79-5a60f134c98b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cgs-number</name>
      <type>Main</type>
      <value>{&quot;msg&quot;:&quot;Please enter number only&quot;}</value>
      <webElementGuid>41857601-0fbe-41e5-9f35-d84c4c0ca3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cgs-display</name>
      <type>Main</type>
      <value>fzip_error</value>
      <webElementGuid>68a7e093-5454-47d2-9a5b-6faef114a592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtZip&quot;)</value>
      <webElementGuid>93c3f381-a726-48d1-a71a-d1878d2ccfa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtZip']</value>
      <webElementGuid>57989b70-53e1-45aa-bdbb-c201dd0b492b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-details']/div/div[4]/div/input</value>
      <webElementGuid>2442f8d6-1ec7-4c9e-bd57-bf2d0b6805d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>eae32d73-35ca-44d6-94dc-89602fdb22c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtZip' and @placeholder = 'Zip/Postal Code']</value>
      <webElementGuid>6e44615d-4b09-4e73-aac3-c9c3c6fdcf58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
